//@version=2
strategy("Chiến lược Heikin Ashi V2", shorttitle="HAS V2")
res = input(title="Khung thời gian nến Heikin Ashi", type=resolution, defval="60")
hshift = input(1, title="Dịch chuyển khung thời gian nến Heikin Ashi")
res1 = input(title="Khung thời gian EMA Heikin Ashi", type=resolution, defval="180")
mhshift = input(0, title="Dịch chuyển khung thời gian EMA Heikin Ashi")
fama = input(1, "Giai đoạn EMA Heikin Ashi")
test = input(1, "Dịch chuyển EMA Heikin Ashi")
sloma = input(30, "Giai đoạn EMA chậm")
slomas = input(1, "Dịch chuyển EMA chậm")
macdf = input(false, title="Sử dụng bộ lọc MACD")
res2 = input(title="Khung thời gian MACD", type=resolution, defval="15")
macds = input(1, title="Dịch chuyển MACD")

// Giá mở/đóng của nến Heikin Ashi
ha_t = heikinashi(tickerid)
ha_open = security(ha_t, res, open[hshift])
ha_close = security(ha_t, res, close[hshift])
mha_close = security(ha_t, res1, close[mhshift])

// MACD
[macdLine, signalLine, histLine] = macd(close, 12, 26, 9)
macdl = security(ha_t, res2, macdLine[macds])
macdsl = security(ha_t, res2, signalLine[macds])

// Trung bình di chuyển
fma = ema(mha_close[test], fama)
sma = ema(ha_close[slomas], sloma)
plot(fma, title="EMA", color=lime, linewidth=1, style=line)
plot(sma, title="EMA chậm", color=red, linewidth=1, style=line)

// Chiến lược
// Mua khi EMA nhanh cắt lên trên EMA chậm và MACD > MACD Signal
// Bán khi EMA nhanh cắt xuống dưới EMA chậm và MACD < MACD Signal
golong = crossover(fma, sma) and (macdl > macdsl or macdf == false)
goshort = crossunder(fma, sma) and (macdl < macdsl or macdf == false)

// Đóng lệnh khi có tín hiệu ngược lại
strategy.entry("Long", strategy.long, when=golong)
strategy.entry("Short", strategy.short, when=goshort)